name: dogfinder

description: "A Flutter mobile application that explores dog breeds and images using The Dog API."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
